services:
  app:
    build: .
    network_mode: bridge
    restart: unless-stopped
    ports:
      - "127.0.0.1:8100:8100"
    environment:
      - BANK_APP_MODE=release
      - BANK_APP_SWAGGER_ENABLED=1
