[postgres]
username = ""
host = ""
port = ""
dbname = ""
password = ""
sslmode = "disable"
timezone = "Europe/Moscow"

[auth]
jwtsignkey = ""

[server]
port = ""
tls_enabled = false
cert = ""
key = ""
